import "./globals.css";
import { SidebarProvider } from '@/contexts/SidebarContext';
import Sidebar from '@/components/Sidebar';

export const metadata = {
  title: "Formações BEI Educação - Módulo 3",
  description: "Generated by Hélio Sales Jr.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <div className="relative">
            <Sidebar />
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}